### ISSUE TITLE
当在JS文件中Import css 文件时，编译报错

### ISSUE THREAD

**Issue by ouminghai** [xwpongithub/webpack-multipage-cli#1]
ERROR in ./~/postcss-loader?{}!./~/css-loader?{"minimize":true}!./~/element-ui/lib/theme-default/index.css
Module build failed: Unknown word (1:1)

> 1 | exports = module.exports = require("../../../css-loader/lib/css-base.js")();
    | ^
  2 | // imports
  3 |

 @ ./~/element-ui/lib/theme-default/index.css 4:14-120
 @ ./src/modules/Channel/Channel.js

**Comment by xwpongithub** [comment]
已修复此bug，请重新下载新版本

**Comment by xwpongithub** [comment]
请下载release的1.2.2版本，1.2.1经过我测试在build模式下依然有此问题
