### ISSUE TITLE
最新版在 npm run dev 后报错

### ISSUE THREAD

**Issue by LiberoFile** [xwpongithub/webpack-multipage-cli#2]
ERROR  Failed to compile with 4 errors                                                                                                               17:23:06

These dependencies were not found:

* styl/index in ./src/js/index.js
* styl/user in ./src/js/user.js
* element-ui/lib/theme-default/index.css in ./src/js/index.js
* !!vue-style-loader!css-loader?{"minimize":false,"sourceMap":true}!../../../node_modules/vue-loader/lib/style-compiler/index?{"id":"data-v-54236e6e","scoped":false,"hasInlineConfig":true}!stylus-loader?{"sourceMap":true}!../../../node_modules/vue-loader/lib/selector?type=styles&index=0!./Index.vue in ./src/modules/Index/Index.vue

To install them, you can run: npm install --save styl/index styl/user element-ui/lib/theme-default/index.css !!vue-style-loader!css-loader?{"minimize":false,"sourceMap":true}!../../../node_modules/vue-loader/lib/style-compiler/index?{"id":"data-v-54236e6e","scoped":false,"hasInlineConfig":true}!stylus-loader?{"sourceMap":true}!../../../node_modules/vue-loader/lib/selector?type=styles&index=0!./Index.vue

**Comment by xwpongithub** [comment]
经测试并未发现最新版的有报这个错误，请删除你之前下好的node_modules目录并重新npm install一下，可能会有影响

**Comment by xwpongithub** [comment]
已检查出为什么会出现这个错误，原因还是依赖的问题（忘记把stylus,stylus-loader,postcss-loader加入到package.json中），现在已经更新了package.json了，请根据新的package.json来重新npm install下你的依赖应该就没问题了，有问题再向我反应哈

**Comment by LiberoFile** [comment]
谢谢！
