### ISSUE TITLE
多入口添加路由问题

### ISSUE THREAD

**Issue by LiberoFile** [xwpongithub/webpack-multipage-cli#3]
我想着在两个不同入口都用路由。
http://localhost:8080，在这个入口，加入路由（vue-router），可以正常使用，在http://localhost:8082/pages/user.html 这个入口，我加入路由没反应。能帮我解答一下吗？

**Comment by LiberoFile** [comment]
问题算是解决了一半。http://localhost:8080这个入口，路由模式可以是 hash 或者 history 。第二个入口的路由模式则只能是 hash。

**Comment by xwpongithub** [comment]
我个人是不推荐history路由模式的（虽然hash丑一点），而且如果使用了多入口并且采用了vue-router的话，history模式就会产生你说的这种问题
