### ISSUE TITLE
关于发布的问题

### ISSUE THREAD

**Issue by gyx1986** [xwpongithub/webpack-multipage-cli#4]
你好，麻烦问下，我用咱们这个多页面脚手架来构建项目，定义了两个子模块页面，但是，run build之后，虽然有两个页面，可是内容完全一样，我看咱们的说明里面有写需要在build目录下去配置相应文件，可是build.js里面写的脚本代码却是自动匹配的，这个需要写在哪里？还是我哪里用的不对，如果有时间，还望解答下，非常感谢。

**Comment by xwpongithub** [comment]
不用再进行配置了啊，build出来的东西直接就放到了dist目录下，只需要按照对应结构组织src目录下的modules目录中的文件目录就行了。
